# Fix Calendar API Access

print("CALENDAR API FIX - Follow these exact steps:")
print("=" * 50)
print()
print("STEP 1: Enable Calendar API")
print("1. Go to: https://console.cloud.google.com/apis/library/calendar-json.googleapis.com")
print("2. Make sure project 869594859370 is selected")
print("3. Click 'ENABLE' button")
print()
print("STEP 2: Update OAuth Scopes (CRITICAL)")
print("Your current credentials only have Gmail scope.")
print("You need to add Calendar scope and regenerate token.")
print()
print("4. Delete your current token.json file")
print("5. Run the bot again - it will ask for new permissions")
print("6. When Google asks for permissions, grant BOTH:")
print("   - Gmail access")
print("   - Calendar access")
print()
print("STEP 3: Test")
print("7. Use !check command in Discord")
print()
print("The error means Google doesn't recognize your app for Calendar API.")
print("This happens when credentials lack Calendar scope.")